SmartCardContext.getStatusChange() algorithm
WICG/web-smart-card pull request #14
Opened 2023-07-25 12:40 UTC by dandrader

2023-07-25 23:35 UTC, reillyeon requested changes

2023-07-25 23:35 UTC, reillyeon commented on index.html
> +            <li>Set |dword| to the bitwise OR of |dword| and |shiftedN|.</li>
Clear the high bits of `dword` first?

2023-07-25 23:35 UTC, reillyeon commented on index.html
> +              <li>Let |flagsIn:SmartCardReaderStateFlagsIn| be that given
```suggestion
              <li>Let |flagsIn:SmartCardReaderStateFlagsIn| be the given
```

2023-07-25 23:35 UTC, reillyeon commented on index.html
> +                  considered in this speficiation as existing PC/SC
```suggestion
                  considered in this specification as existing PC/SC
```

2023-07-25 23:35 UTC, reillyeon commented on index.html
> +                    still considered in this speficiation as several existing
```suggestion
                    still considered in this specification as several existing
```

2023-07-25 23:35 UTC, reillyeon commented on index.html
> +                    avaialble, the upper two bytes of `EventState` will always
```suggestion
                    available, the upper two bytes of `EventState` will always
```

2023-07-25 23:35 UTC, reillyeon commented on index.html
> +                    "{{SmartCardReaderStateOut/eventCount}}".</p>
```suggestion
                    "{{SmartCardReaderStateOut/eventCount}}" will be zero.</p>
```

2023-07-26 12:05 UTC, dandrader commented on index.html
> +            <li>Set |dword| to the bitwise OR of |dword| and |shiftedN|.</li>
Oops! Fixed, thanks!

2023-07-26 20:06 UTC, reillyeon approved these changes

2023-07-27 07:46 UTC, merged